// Radius Defect Checklist — investor report review
//
// Lets a manager (same REVIEW_SECRET as the regular review queue) see every
// draft investor report generated by generate-investor-reports.js, and mark
// one Approved once it's been checked. This never sends anything anywhere —
// approving just unlocks the "Download PDF" step, which is a real PDF built
// in the browser from the report's data, for you to send however you
// normally send investor correspondence.
//
// Required Netlify environment variables (same as the rest of the tool):
//   GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO, GITHUB_BRANCH (optional)
//   REVIEW_SECRET

const GITHUB_API = 'https://api.github.com';

exports.handler = async (event) => {
  const REVIEW_SECRET = process.env.REVIEW_SECRET;
  const suppliedKey = event.headers['x-review-key'] || event.headers['X-Review-Key'];
  if (REVIEW_SECRET && suppliedKey !== REVIEW_SECRET) {
    return { statusCode: 401, body: JSON.stringify({ error: 'Invalid or missing manager review key.' }) };
  }

  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  const branch = process.env.GITHUB_BRANCH || 'main';
  if (!token || !owner || !repo) {
    return { statusCode: 500, body: JSON.stringify({ error: 'Server is not configured yet.' }) };
  }

  function ghHeaders() {
    return {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'User-Agent': 'radius-defect-checklist-tool'
    };
  }
  async function ghGetRaw(path) {
    const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${path}?ref=${branch}`, { headers: ghHeaders() });
    if (res.status === 404) return { exists: false };
    if (!res.ok) throw new Error('GitHub GET ' + path + ' failed (' + res.status + ')');
    const j = await res.json();
    if (j.content) return { exists: true, sha: j.sha, content: j.content };
    if (j.sha) {
      const blobRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/blobs/${j.sha}`, { headers: ghHeaders() });
      if (blobRes.ok) {
        const blobJson = await blobRes.json();
        return { exists: true, sha: j.sha, content: (blobJson.content || '').replace(/\n/g, '') };
      }
    }
    return { exists: true, sha: j.sha, content: '' };
  }
  async function ghPutContent(path, contentBase64, message, sha) {
    const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT', headers: ghHeaders(),
      body: JSON.stringify({ message, content: contentBase64, branch, ...(sha ? { sha } : {}) })
    });
    if (!res.ok) throw new Error('GitHub PUT failed (' + res.status + '): ' + (await res.text()));
    return res.json();
  }

  const REG_PATH = 'investor-reports/registry.json';
  const DOWNLOAD_CHUNK_SIZE = 900000;

  async function getRegistry() {
    const r = await ghGetRaw(REG_PATH);
    if (!r.exists) return { sha: null, list: [] };
    return { sha: r.sha, list: JSON.parse(Buffer.from(r.content, 'base64').toString('utf-8')) };
  }

  const qp = event.queryStringParameters || {};

  // ---- GET: fetch a specific report's data (chunked, same as PDF viewing elsewhere) ----
  if (event.httpMethod === 'GET' && qp.data) {
    const slug = String(qp.data).replace(/[^a-zA-Z0-9_\-]/g, '-');
    const chunkIndex = parseInt(qp.chunk || '0', 10);
    try {
      const { list } = await getRegistry();
      const entry = list.find(r => r.slug === slug);
      if (!entry) return { statusCode: 404, body: JSON.stringify({ error: 'Report not found.' }) };
      const fileR = await ghGetRaw(entry.dataPath);
      if (!fileR.exists) return { statusCode: 404, body: JSON.stringify({ error: 'Report data file not found.' }) };
      const fullBase64 = fileR.content;
      const totalChunks = Math.max(Math.ceil(fullBase64.length / DOWNLOAD_CHUNK_SIZE), 1);
      const chunkData = fullBase64.slice(chunkIndex * DOWNLOAD_CHUNK_SIZE, (chunkIndex + 1) * DOWNLOAD_CHUNK_SIZE);
      return { statusCode: 200, body: JSON.stringify({ ok: true, chunkData, chunkIndex, totalChunks, entry }) };
    } catch (err) {
      return { statusCode: 500, body: JSON.stringify({ error: String(err && err.message ? err.message : err) }) };
    }
  }

  // ---- POST: approve a report ----
  if (event.httpMethod === 'POST') {
    let payload;
    try { payload = JSON.parse(event.body); } catch (e) { return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) }; }
    const { slug, action } = payload;
    if (!slug || action !== 'approve') return { statusCode: 400, body: JSON.stringify({ error: 'Missing slug, or unsupported action.' }) };
    try {
      const { list, sha } = await getRegistry();
      const idx = list.findIndex(r => r.slug === slug);
      if (idx === -1) return { statusCode: 404, body: JSON.stringify({ error: 'Report not found.' }) };
      list[idx].status = 'approved';
      list[idx].reviewedAt = new Date().toISOString();
      await ghPutContent(REG_PATH, Buffer.from(JSON.stringify(list, null, 2), 'utf-8').toString('base64'), `Investor report approved: ${slug}`, sha);
      return { statusCode: 200, body: JSON.stringify({ ok: true }) };
    } catch (err) {
      return { statusCode: 500, body: JSON.stringify({ error: String(err && err.message ? err.message : err) }) };
    }
  }

  // ---- GET: list all draft/approved reports ----
  try {
    const { list } = await getRegistry();
    return { statusCode: 200, body: JSON.stringify({ ok: true, list }) };
  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ error: String(err && err.message ? err.message : err) }) };
  }
};
